Alvaro Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #112
Opened 2023-10-05 13:28 UTC by alvarodelser

Assignment 4 Submission. Includes Assignment 3 as well (from pull Request #110 )

2023-11-16 00:20 UTC, dgarijo commented
This branch has conflicts on files that I cannot see. I can't merge it in its current state

2023-11-16 00:23 UTC, dgarijo requested changes
Please address missing comments

2023-11-16 00:23 UTC, dgarijo commented on Assignment4/alvarodelser-071479466/task07.py
> +# Visualize the results
Missing all exercises in rdflib

2023-11-16 00:23 UTC, dgarijo commented on Assignment4/alvarodelser-071479466/task06.py
> +g.add((ns.JohnSmith, VCARD.Works, ns.UPM))
vcard does not define `Works`. Create your own property or find another vocabulary that does

2023-11-27 21:11 UTC, anaigmo commented
Submitted and graded. The PR is conflictive and contains more files than the specified for the assignment, closing without merge

2023-11-27 21:11 UTC, closed without merging