python
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #179
Opened 2023-10-09 18:18 UTC by MeisiSaalim

2023-11-17 17:31 UTC, dgarijo requested changes
Please address remaining issues

2023-11-17 17:31 UTC, dgarijo commented on Assignment4/MeisiSaalim-0X9230823/task07.py
> +                ?subClass rdfs:subClassOf ns:LivingThing .
Does not retrieve subclasses of subclasses of living thing. Use `*`

2023-11-17 17:31 UTC, dgarijo commented on Assignment4/MeisiSaalim-0X9230823/task07.py
> +for subClass, _, _ in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
Same issue as below. Use a recursive function

2023-11-17 17:31 UTC, dgarijo commented on Assignment4/MeisiSaalim-0X9230823/task07.py
> +
Several exercises missing in rdflib!

2023-11-27 21:28 UTC, anaigmo commented
Submitted and mostly fixed, no more PRs allowed

2023-11-27 21:28 UTC, merged