Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #183
Opened 2023-10-09 18:57 UTC by miikeldela

2023-11-16 09:48 UTC, dgarijo requested changes
Please see pending comments to review

2023-11-16 09:48 UTC, dgarijo commented on Assignment4/miikeldela-23A284/task06.py
> +g.add((ns.JohnSmith, VCARD.Works, ns.UPM))
You should not create new properties in a vocabulary you don't own. Instead, create one yourself in a new namespace.

2023-11-16 09:48 UTC, dgarijo commented on Assignment4/miikeldela-23A284/task07.py
> +    ?Subject rdfs:subClassOf ns:LivingThing.
You are not listing subclasses of subclasses of living thing

2023-11-16 09:48 UTC, dgarijo commented on Assignment4/miikeldela-23A284/task07.py
> +for s, p, o in g.triples((None,RDFS.subClassOf,ns.LivingThing)):
You are not listing subclasses of subclasses of living thing. Hint: use a recursive function

2023-11-16 09:48 UTC, dgarijo commented on Assignment4/miikeldela-23A284/task07.py
> +  initNs = { "rdfs": RDFS, "ns":ns}
same issue as above for both rdflib/sparql

2023-11-16 09:48 UTC, dgarijo commented on Assignment4/miikeldela-23A284/task07.py
> +    FILTER (?pers IN (ns:Animal, ns:Person))
Use union instead of filter here. This is a very costly query otherwise

2023-11-16 09:48 UTC, dgarijo commented on Assignment4/miikeldela-23A284/task07.py
> +    ?Subject foaf:knows ns:RockySmith.
the exercise is asking to return the **name** of the persons who know rocky. Other animals may know rocky

2023-11-16 09:48 UTC, dgarijo commented on Assignment4/miikeldela-23A284/task07.py
> +for s, p, o in g.triples((None,FOAF.knows,ns.RockySmith)):
the exercise is asking to return the name of the persons who know rocky. Other animals may know rocky

2023-11-27 21:24 UTC, anaigmo commented
Submitted and graded, additional files in PR so not merging

2023-11-27 21:24 UTC, closed without merging