Assignment4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #192
Opened 2023-10-10 10:47 UTC by AliciaMorMar

Addign tasks 6, 7, 8 and 9 of assignment 4

2023-11-17 17:24 UTC, dgarijo requested changes
Some changes pending. It's going in the right direction

2023-11-17 17:24 UTC, dgarijo commented on Assignment4/AliciaMorMar-23A262/task06.py
> +g.add((ns.JohnSmith, VCARD.WorkPlace, ns.UPM))
This property does not exist in VCARD. Search for a property that exists or create your own

2023-11-17 17:24 UTC, dgarijo commented on Assignment4/AliciaMorMar-23A262/task07.py
> +    ?subclass rdfs:subClassOf ns:LivingThing.
Missing all subclasses of subclasses of living thing (use `*`)

2023-11-17 17:24 UTC, dgarijo commented on Assignment4/AliciaMorMar-23A262/task07.py
> +      FILTER(?thing = ns:Person || ?thing = ns:Animal)
very inefficent query. Use UNIOn instead

2023-11-17 17:24 UTC, dgarijo commented on Assignment4/AliciaMorMar-23A262/task07.py
> +       ?person foaf:knows ns:RockySmith .
see what the exercise is asking to return. Not a URI, but a name

2023-11-17 17:24 UTC, dgarijo commented on Assignment4/AliciaMorMar-23A262/task07.py
> +for r in g.query(q5):
Missing all exercises in rdflib

2023-11-17 18:05 UTC, AliciaMorMar commented
Buenas Daniel,

Hasta que fecha dispongo para realizar estos cambios?

Un saludo,
Alicia

El vie, 17 nov 2023 a las 18:24, Daniel Garijo ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Some changes pending. It's going in the right direction
> ------------------------------
>
> In Assignment4/AliciaMorMar-23A262/task06.py
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638661>
> :
>
> > +# TO DO
> +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
> +
> +g.add((ns.JaneSmith, VCARD.EMAIL, ***@***.***")))
> +g.add((ns.JaneSmith, VCARD.FN, Literal("Jane Smith")))
> +g.add((ns.JaneSmith, VCARD.Given, Literal("Jane")))
> +g.add((ns.JaneSmith, VCARD.Family, Literal("Smith")))
> +# Visualize the results
> +for s, p, o in g.triples((ns.JaneSmith,None,None)):
> +  print(s,p,o)
> +
> +"""**TASK 6.5: Add UPM as the university where John Smith works**"""
> +
> +# TO DO
> +g.add((ns.UPM, RDF.type, ns.University))
> +g.add((ns.JohnSmith, VCARD.WorkPlace, ns.UPM))
>
> This property does not exist in VCARD. Search for a property that exists
> or create your own
> ------------------------------
>
> In Assignment4/AliciaMorMar-23A262/task07.py
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638925>
> :
>
> > +from rdflib import Graph, Namespace, Literal
> +from rdflib.namespace import RDF, RDFS
> +g = Graph()
> +g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
> +g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
> +g.parse(github_storage+"/rdf/example6.rdf", format="xml")
> +
> +"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""
> +
> +# TO DO
> +from rdflib.plugins.sparql import prepareQuery
> +NS = Namespace("http://somewhere#")
> +
> +q1 = prepareQuery('''
> +  SELECT ?subclass WHERE {
> +    ?subclass rdfs:subClassOf ns:LivingThing.
>
> Missing all subclasses of subclasses of living thing (use *)
> ------------------------------
>
> In Assignment4/AliciaMorMar-23A262/task07.py
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644025>
> :
>
> > +)
> +
> +# Visualize the results
> +for r in g.query(q2):
> +  print(r.individual)
> +
> +"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**
> +
> +"""
> +
> +# TO DO
> +q3 = prepareQuery('''
> +  SELECT ?individual ?thing ?prop ?clas WHERE {
> +      ?individual rdf:type ?thing.
> +      ?individual ?prop ?clas
> +      FILTER(?thing = ns:Person || ?thing = ns:Animal)
>
> very inefficent query. Use UNIOn instead
> ------------------------------
>
> In Assignment4/AliciaMorMar-23A262/task07.py
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644954>
> :
>
> > +)
> +
> +# Visualize the results
> +for r in g.query(q3):
> +  print(r.individual, r.thing, r.prop, r.clas)
> +
> +"""**TASK 7.4:  List the name of the persons who know Rocky**"""
> +
> +# TO DO
> +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0")
> +from rdflib.namespace import FOAF
> +
> +q4 = prepareQuery('''
> +    SELECT DISTINCT ?person
> +    WHERE {
> +       ?person foaf:knows ns:RockySmith .
>
> see what the exercise is asking to return. Not a URI, but a name
> ------------------------------
>
> In Assignment4/AliciaMorMar-23A262/task07.py
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397646379>
> :
>
> > +
> +# TO DO
> +q5 = prepareQuery('''
> +  SELECT DISTINCT ?entity  WHERE
> +  {
> +    ?entity foaf:knows ?person.
> +    FILTER(?entity != ?person).
> +  }
> +  GROUP BY ?entity
> +  HAVING (COUNT(DISTINCT ?person) >= 2)
> +  ''',
> +  initNs = {"foaf":FOAF}
> +)
> +
> +# Visualize the results
> +for r in g.query(q5):
>
> Missing all exercises in rdflib
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#pullrequestreview-1737518674>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCSYUTNL42TLIWYCXDZHE2DYE6MUHAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZXGUYTQNRXGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/review/1737518674
> @github.com>
>

2023-11-17 18:09 UTC, dgarijo commented
1 semana. He puesto un mensaje en el foro

El vie., 17 nov. 2023 7:05 p. m., AliciaMorMar ***@***.***>
escribió:

> Buenas Daniel,
>
> Hasta que fecha dispongo para realizar estos cambios?
>
> Un saludo,
> Alicia
>
> El vie, 17 nov 2023 a las 18:24, Daniel Garijo ***@***.***>)
> escribió:
>
> > ***@***.**** requested changes on this pull request.
> >
> > Some changes pending. It's going in the right direction
> > ------------------------------
> >
> > In Assignment4/AliciaMorMar-23A262/task06.py
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638661>
>
> > :
> >
> > > +# TO DO
> > +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
> > +
> > +g.add((ns.JaneSmith, VCARD.EMAIL, ***@***.***")))
> > +g.add((ns.JaneSmith, VCARD.FN, Literal("Jane Smith")))
> > +g.add((ns.JaneSmith, VCARD.Given, Literal("Jane")))
> > +g.add((ns.JaneSmith, VCARD.Family, Literal("Smith")))
> > +# Visualize the results
> > +for s, p, o in g.triples((ns.JaneSmith,None,None)):
> > + print(s,p,o)
> > +
> > +"""**TASK 6.5: Add UPM as the university where John Smith works**"""
> > +
> > +# TO DO
> > +g.add((ns.UPM, RDF.type, ns.University))
> > +g.add((ns.JohnSmith, VCARD.WorkPlace, ns.UPM))
> >
> > This property does not exist in VCARD. Search for a property that exists
> > or create your own
> > ------------------------------
> >
> > In Assignment4/AliciaMorMar-23A262/task07.py
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638925>
>
> > :
> >
> > > +from rdflib import Graph, Namespace, Literal
> > +from rdflib.namespace import RDF, RDFS
> > +g = Graph()
> > +g.namespace_manager.bind('ns', Namespace("http://somewhere#"),
> override=False)
> > +g.namespace_manager.bind('vcard', Namespace("
> http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
> > +g.parse(github_storage+"/rdf/example6.rdf", format="xml")
> > +
> > +"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and
> SPARQL**"""
> > +
> > +# TO DO
> > +from rdflib.plugins.sparql import prepareQuery
> > +NS = Namespace("http://somewhere#")
> > +
> > +q1 = prepareQuery('''
> > + SELECT ?subclass WHERE {
> > + ?subclass rdfs:subClassOf ns:LivingThing.
> >
> > Missing all subclasses of subclasses of living thing (use *)
> > ------------------------------
> >
> > In Assignment4/AliciaMorMar-23A262/task07.py
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644025>
>
> > :
> >
> > > +)
> > +
> > +# Visualize the results
> > +for r in g.query(q2):
> > + print(r.individual)
> > +
> > +"""**TASK 7.3: List all individuals of "Person" or "Animal" and all
> their properties including their class with RDFLib and SPARQL. You do not
> need to list the individuals of the subclasses of person**
> > +
> > +"""
> > +
> > +# TO DO
> > +q3 = prepareQuery('''
> > + SELECT ?individual ?thing ?prop ?clas WHERE {
> > + ?individual rdf:type ?thing.
> > + ?individual ?prop ?clas
> > + FILTER(?thing = ns:Person || ?thing = ns:Animal)
> >
> > very inefficent query. Use UNIOn instead
> > ------------------------------
> >
> > In Assignment4/AliciaMorMar-23A262/task07.py
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644954>
>
> > :
> >
> > > +)
> > +
> > +# Visualize the results
> > +for r in g.query(q3):
> > + print(r.individual, r.thing, r.prop, r.clas)
> > +
> > +"""**TASK 7.4: List the name of the persons who know Rocky**"""
> > +
> > +# TO DO
> > +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0")
> > +from rdflib.namespace import FOAF
> > +
> > +q4 = prepareQuery('''
> > + SELECT DISTINCT ?person
> > + WHERE {
> > + ?person foaf:knows ns:RockySmith .
> >
> > see what the exercise is asking to return. Not a URI, but a name
> > ------------------------------
> >
> > In Assignment4/AliciaMorMar-23A262/task07.py
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397646379>
>
> > :
> >
> > > +
> > +# TO DO
> > +q5 = prepareQuery('''
> > + SELECT DISTINCT ?entity WHERE
> > + {
> > + ?entity foaf:knows ?person.
> > + FILTER(?entity != ?person).
> > + }
> > + GROUP BY ?entity
> > + HAVING (COUNT(DISTINCT ?person) >= 2)
> > + ''',
> > + initNs = {"foaf":FOAF}
> > +)
> > +
> > +# Visualize the results
> > +for r in g.query(q5):
> >
> > Missing all exercises in rdflib
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#pullrequestreview-1737518674>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BCSYUTNL42TLIWYCXDZHE2DYE6MUHAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZXGUYTQNRXGQ>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> >
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/review/1737518674
>
> > @github.com>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#issuecomment-1816868864>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALTIGQL5XNHDQQSLV2QDU3YE6ROHAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJWHA3DQOBWGQ>
> .
> You are receiving this because you commented.Message ID:
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/c1816868864@
> github.com>
>

2023-11-17 18:11 UTC, AliciaMorMar commented
Perfecto, muchas gracias

El vie, 17 nov 2023 a las 19:09, Daniel Garijo ***@***.***>)
escribió:

> 1 semana. He puesto un mensaje en el foro
>
> El vie., 17 nov. 2023 7:05 p. m., AliciaMorMar ***@***.***>
> escribió:
>
> > Buenas Daniel,
> >
> > Hasta que fecha dispongo para realizar estos cambios?
> >
> > Un saludo,
> > Alicia
> >
> > El vie, 17 nov 2023 a las 18:24, Daniel Garijo ***@***.***>)
> > escribió:
> >
> > > ***@***.**** requested changes on this pull request.
> > >
> > > Some changes pending. It's going in the right direction
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task06.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638661>
>
> >
> > > :
> > >
> > > > +# TO DO
> > > +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
> > > +
> > > +g.add((ns.JaneSmith, VCARD.EMAIL, ***@***.***")))
> > > +g.add((ns.JaneSmith, VCARD.FN, Literal("Jane Smith")))
> > > +g.add((ns.JaneSmith, VCARD.Given, Literal("Jane")))
> > > +g.add((ns.JaneSmith, VCARD.Family, Literal("Smith")))
> > > +# Visualize the results
> > > +for s, p, o in g.triples((ns.JaneSmith,None,None)):
> > > + print(s,p,o)
> > > +
> > > +"""**TASK 6.5: Add UPM as the university where John Smith works**"""
> > > +
> > > +# TO DO
> > > +g.add((ns.UPM, RDF.type, ns.University))
> > > +g.add((ns.JohnSmith, VCARD.WorkPlace, ns.UPM))
> > >
> > > This property does not exist in VCARD. Search for a property that
> exists
> > > or create your own
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638925>
>
> >
> > > :
> > >
> > > > +from rdflib import Graph, Namespace, Literal
> > > +from rdflib.namespace import RDF, RDFS
> > > +g = Graph()
> > > +g.namespace_manager.bind('ns', Namespace("http://somewhere#"),
> > override=False)
> > > +g.namespace_manager.bind('vcard', Namespace("
> > http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
> > > +g.parse(github_storage+"/rdf/example6.rdf", format="xml")
> > > +
> > > +"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and
> > SPARQL**"""
> > > +
> > > +# TO DO
> > > +from rdflib.plugins.sparql import prepareQuery
> > > +NS = Namespace("http://somewhere#")
> > > +
> > > +q1 = prepareQuery('''
> > > + SELECT ?subclass WHERE {
> > > + ?subclass rdfs:subClassOf ns:LivingThing.
> > >
> > > Missing all subclasses of subclasses of living thing (use *)
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644025>
>
> >
> > > :
> > >
> > > > +)
> > > +
> > > +# Visualize the results
> > > +for r in g.query(q2):
> > > + print(r.individual)
> > > +
> > > +"""**TASK 7.3: List all individuals of "Person" or "Animal" and all
> > their properties including their class with RDFLib and SPARQL. You do
> not
> > need to list the individuals of the subclasses of person**
> > > +
> > > +"""
> > > +
> > > +# TO DO
> > > +q3 = prepareQuery('''
> > > + SELECT ?individual ?thing ?prop ?clas WHERE {
> > > + ?individual rdf:type ?thing.
> > > + ?individual ?prop ?clas
> > > + FILTER(?thing = ns:Person || ?thing = ns:Animal)
> > >
> > > very inefficent query. Use UNIOn instead
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644954>
>
> >
> > > :
> > >
> > > > +)
> > > +
> > > +# Visualize the results
> > > +for r in g.query(q3):
> > > + print(r.individual, r.thing, r.prop, r.clas)
> > > +
> > > +"""**TASK 7.4: List the name of the persons who know Rocky**"""
> > > +
> > > +# TO DO
> > > +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0")
> > > +from rdflib.namespace import FOAF
> > > +
> > > +q4 = prepareQuery('''
> > > + SELECT DISTINCT ?person
> > > + WHERE {
> > > + ?person foaf:knows ns:RockySmith .
> > >
> > > see what the exercise is asking to return. Not a URI, but a name
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397646379>
>
> >
> > > :
> > >
> > > > +
> > > +# TO DO
> > > +q5 = prepareQuery('''
> > > + SELECT DISTINCT ?entity WHERE
> > > + {
> > > + ?entity foaf:knows ?person.
> > > + FILTER(?entity != ?person).
> > > + }
> > > + GROUP BY ?entity
> > > + HAVING (COUNT(DISTINCT ?person) >= 2)
> > > + ''',
> > > + initNs = {"foaf":FOAF}
> > > +)
> > > +
> > > +# Visualize the results
> > > +for r in g.query(q5):
> > >
> > > Missing all exercises in rdflib
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#pullrequestreview-1737518674>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/BCSYUTNL42TLIWYCXDZHE2DYE6MUHAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZXGUYTQNRXGQ>
>
> >
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > >
> >
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/review/1737518674
>
> >
> > > @github.com>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#issuecomment-1816868864>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AALTIGQL5XNHDQQSLV2QDU3YE6ROHAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJWHA3DQOBWGQ>
>
> > .
> > You are receiving this because you commented.Message ID:
> > <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/c1816868864@
> > github.com>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#issuecomment-1816874326>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCSYUTIFHDVCPSQY26WJWCLYE6R6JAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJWHA3TIMZSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/c1816874326@
> github.com>
>

2023-11-26 11:58 UTC, AliciaMorMar commented
Buenas,

El pasado viernes le mandé un correo con el Assigment 4 actualizado con las
correcciones, se lo mandé al correo de ***@***.***", porque
constantemente me saltaba un error git y no me dejaba hacer el 'push
request'. Lo menciono por aquí por si no llega a ver antes el otro mail. Si
tengo que subirlo si o si a github agradecería que me permitiesen hacerlo
aunque sea fuera de plazo... pero como no lo conseguía mandé por ello un
mail el viernes con los updates.

Un saludo,
Alicia

El vie, 17 nov 2023 a las 19:09, Daniel Garijo ***@***.***>)
escribió:

> 1 semana. He puesto un mensaje en el foro
>
> El vie., 17 nov. 2023 7:05 p. m., AliciaMorMar ***@***.***>
> escribió:
>
> > Buenas Daniel,
> >
> > Hasta que fecha dispongo para realizar estos cambios?
> >
> > Un saludo,
> > Alicia
> >
> > El vie, 17 nov 2023 a las 18:24, Daniel Garijo ***@***.***>)
> > escribió:
> >
> > > ***@***.**** requested changes on this pull request.
> > >
> > > Some changes pending. It's going in the right direction
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task06.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638661>
>
> >
> > > :
> > >
> > > > +# TO DO
> > > +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
> > > +
> > > +g.add((ns.JaneSmith, VCARD.EMAIL, ***@***.***")))
> > > +g.add((ns.JaneSmith, VCARD.FN, Literal("Jane Smith")))
> > > +g.add((ns.JaneSmith, VCARD.Given, Literal("Jane")))
> > > +g.add((ns.JaneSmith, VCARD.Family, Literal("Smith")))
> > > +# Visualize the results
> > > +for s, p, o in g.triples((ns.JaneSmith,None,None)):
> > > + print(s,p,o)
> > > +
> > > +"""**TASK 6.5: Add UPM as the university where John Smith works**"""
> > > +
> > > +# TO DO
> > > +g.add((ns.UPM, RDF.type, ns.University))
> > > +g.add((ns.JohnSmith, VCARD.WorkPlace, ns.UPM))
> > >
> > > This property does not exist in VCARD. Search for a property that
> exists
> > > or create your own
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397638925>
>
> >
> > > :
> > >
> > > > +from rdflib import Graph, Namespace, Literal
> > > +from rdflib.namespace import RDF, RDFS
> > > +g = Graph()
> > > +g.namespace_manager.bind('ns', Namespace("http://somewhere#"),
> > override=False)
> > > +g.namespace_manager.bind('vcard', Namespace("
> > http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
> > > +g.parse(github_storage+"/rdf/example6.rdf", format="xml")
> > > +
> > > +"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and
> > SPARQL**"""
> > > +
> > > +# TO DO
> > > +from rdflib.plugins.sparql import prepareQuery
> > > +NS = Namespace("http://somewhere#")
> > > +
> > > +q1 = prepareQuery('''
> > > + SELECT ?subclass WHERE {
> > > + ?subclass rdfs:subClassOf ns:LivingThing.
> > >
> > > Missing all subclasses of subclasses of living thing (use *)
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644025>
>
> >
> > > :
> > >
> > > > +)
> > > +
> > > +# Visualize the results
> > > +for r in g.query(q2):
> > > + print(r.individual)
> > > +
> > > +"""**TASK 7.3: List all individuals of "Person" or "Animal" and all
> > their properties including their class with RDFLib and SPARQL. You do
> not
> > need to list the individuals of the subclasses of person**
> > > +
> > > +"""
> > > +
> > > +# TO DO
> > > +q3 = prepareQuery('''
> > > + SELECT ?individual ?thing ?prop ?clas WHERE {
> > > + ?individual rdf:type ?thing.
> > > + ?individual ?prop ?clas
> > > + FILTER(?thing = ns:Person || ?thing = ns:Animal)
> > >
> > > very inefficent query. Use UNIOn instead
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397644954>
>
> >
> > > :
> > >
> > > > +)
> > > +
> > > +# Visualize the results
> > > +for r in g.query(q3):
> > > + print(r.individual, r.thing, r.prop, r.clas)
> > > +
> > > +"""**TASK 7.4: List the name of the persons who know Rocky**"""
> > > +
> > > +# TO DO
> > > +VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0")
> > > +from rdflib.namespace import FOAF
> > > +
> > > +q4 = prepareQuery('''
> > > + SELECT DISTINCT ?person
> > > + WHERE {
> > > + ?person foaf:knows ns:RockySmith .
> > >
> > > see what the exercise is asking to return. Not a URI, but a name
> > > ------------------------------
> > >
> > > In Assignment4/AliciaMorMar-23A262/task07.py
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#discussion_r1397646379>
>
> >
> > > :
> > >
> > > > +
> > > +# TO DO
> > > +q5 = prepareQuery('''
> > > + SELECT DISTINCT ?entity WHERE
> > > + {
> > > + ?entity foaf:knows ?person.
> > > + FILTER(?entity != ?person).
> > > + }
> > > + GROUP BY ?entity
> > > + HAVING (COUNT(DISTINCT ?person) >= 2)
> > > + ''',
> > > + initNs = {"foaf":FOAF}
> > > +)
> > > +
> > > +# Visualize the results
> > > +for r in g.query(q5):
> > >
> > > Missing all exercises in rdflib
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#pullrequestreview-1737518674>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/BCSYUTNL42TLIWYCXDZHE2DYE6MUHAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZXGUYTQNRXGQ>
>
> >
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > >
> >
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/review/1737518674
>
> >
> > > @github.com>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#issuecomment-1816868864>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AALTIGQL5XNHDQQSLV2QDU3YE6ROHAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJWHA3DQOBWGQ>
>
> > .
> > You are receiving this because you commented.Message ID:
> > <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/c1816868864@
> > github.com>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#issuecomment-1816874326>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCSYUTIFHDVCPSQY26WJWCLYE6R6JAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJWHA3TIMZSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/c1816874326@
> github.com>
>

2023-11-26 12:43 UTC, dgarijo commented
@AliciaMorMar subelo en git lo antes posible, por favor. Estamos finalizando las correcciones.

2023-11-26 15:48 UTC, AliciaMorMar commented
Ya lo he conseguido actualizar, siento las molestias, y muchas gracias!

2023-11-26 15:51 UTC, AliciaMorMar commented
Ya lo he conseguido actualizar, siento las molestias, y muchas gracias!


El dom, 26 nov 2023 a las 13:44, Daniel Garijo ***@***.***>)
escribió:

> @AliciaMorMar <https://github.com/AliciaMorMar> subelo en git lo antes
> posible, por favor. Estamos finalizando las correcciones.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192#issuecomment-1826774563>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCSYUTJKPI34I2VSR7CJ66LYGM2RLAVCNFSM6AAAAAA52EPPA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRWG43TINJWGM>
> .
> You are receiving this because you were mentioned.Message ID:
> <FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/192/c1826774563@
> github.com>
>

2023-11-27 21:30 UTC, anaigmo commented
Submitted and graded, no more PRs allowed

2023-11-27 21:31 UTC, merged