Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #193
Opened 2023-10-10 13:34 UTC by bertagh

2023-11-17 17:08 UTC, dgarijo requested changes
Please address remaining changes

2023-11-17 17:08 UTC, dgarijo commented on Assignment4/bertagh-051730600/task07.py
> +  OPTIONAL { ?Entity foaf:knows ?Entity2. FILTER (?Entity1 != ?Entity2) }
wy the optional

2023-11-17 17:08 UTC, dgarijo commented on Assignment4/bertagh-051730600/task07.py
> +      entities.add(s1)
This lists all entities who know someone, but it does not do what the exercise asks for

2023-11-17 17:08 UTC, dgarijo commented on Assignment4/bertagh-051730600/task08.py
> +g1.add((ns.HarryPotter, VCARD.EMAIL, Literal("hpotter@hogwarts.org")))
?? You must not add the knowledge by hand!!

2023-11-27 21:33 UTC, anaigmo commented
Submitted and mostly fixed, no more PRs allowed

2023-11-27 21:33 UTC, merged