Assignment 4 Diego Torrelles
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #198
Opened 2023-10-10 17:25 UTC by diegotorrelles

2023-11-17 16:55 UTC, dgarijo requested changes
Missing many exercises

2023-11-17 16:55 UTC, dgarijo commented on Assignment4/course_materials/DiegoTorrelles-190144/task06.py
> +g.add((ns.JohnSmith, vcard.Works, ns.UPM))
This is not a property in vcard. Search for the right one

2023-11-17 16:55 UTC, dgarijo commented on Assignment4/course_materials/DiegoTorrelles-190144/task06.py
> +  print(s,p,o)
one exercise is missing here

2023-11-17 16:55 UTC, dgarijo commented on Assignment4/course_materials/DiegoTorrelles-190144/task07.py
> +    ?subClass rdfs:subClassOf ns:LivingThing.
this does not retrieve the subclasses of subclasses of Living thing. Use chained properties

2023-11-17 16:55 UTC, dgarijo commented on Assignment4/course_materials/DiegoTorrelles-190144/task07.py
> +      ?subClass rdfs:subClassOf ns:Person.
same issue as above

2023-11-17 16:55 UTC, dgarijo commented on Assignment4/course_materials/DiegoTorrelles-190144/task07.py
> +
missing 7.4, 7.5 and ALL the exercises in rdflib

2023-11-27 21:37 UTC, anaigmo commented
Submitted and mostly fixed, no more PRs allowed. The submission does not follow the instruction, so it will not be merged

2023-11-27 21:37 UTC, closed without merging