Assignment4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #207
Opened 2023-10-11 09:57 UTC by reginalopezentrena

2023-11-17 16:40 UTC, dgarijo requested changes
Please address the issues raised in my review

2023-11-17 16:40 UTC, dgarijo commented on Assignment4/reginalopezentrena-02578881/task07.py
> +    ?Subject RDFS:subClassOf ns:LivingThing.
Does not return subclasses of subclasses of livint thing. Use `*`

2023-11-17 16:40 UTC, dgarijo commented on Assignment4/reginalopezentrena-02578881/task07.py
> +for s, p, o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
Same as above. Make it a recursive function

2023-11-17 16:40 UTC, dgarijo commented on Assignment4/reginalopezentrena-02578881/task07.py
> +    ?Subject RDFS:subClassOf ns:LivingThing.
Does not return subclasses of subclasses of livint thing. Use `*`

2023-11-17 16:40 UTC, dgarijo commented on Assignment4/reginalopezentrena-02578881/task07.py
> +    print(s2)
same as above

2023-11-17 16:40 UTC, dgarijo commented on Assignment4/reginalopezentrena-02578881/task07.py
> +
missing 7.4 and 7.5 in rdflib

2023-11-17 16:40 UTC, dgarijo commented on Assignment4/reginalopezentrena-02578881/task08.py
> +g1.add((ns.SaraJones, vcard.EMAIL, Literal("sara.jones@data.org")))
!!! You have to do it automatically, not by hand!

2023-11-17 16:40 UTC, dgarijo commented on Assignment4/reginalopezentrena-02578881/task09.py
> +g3.add((ns.SaraJones, OWL.sameAs, ns3))
Same as previous exercise

2023-11-27 21:41 UTC, anaigmo commented
Submitted and graded, no more PRs allowed

2023-11-27 21:41 UTC, merged