i do not not know what my studentid is
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #213
Opened 2023-10-11 13:07 UTC by sofiaferben

2023-11-15 22:56 UTC, dgarijo requested changes
Please address these small comments. You almost have it right

2023-11-15 22:56 UTC, dgarijo commented on Assignment4/sofiaferben/task07.py
> +  ?sub rdfs:subClassOf ns:LivingThing.
this will not retrieve the subclasses of subclasses of Living Thing. Hint: use `*`

2023-11-15 22:56 UTC, dgarijo commented on Assignment4/sofiaferben/task07.py
> +  print("Subclass of LivingThing:", s)
This won't retrieve the subclasses of subclasses of Living thing. Hint: make this a recursive function

2023-11-15 22:56 UTC, dgarijo commented on Assignment4/sofiaferben/task07.py
> +        print(s1)
same issue as above

2023-11-15 22:56 UTC, dgarijo commented on Assignment4/sofiaferben/task07.py
> +    print(sub, obj)
you are not listing the properties of the individuals, which is what the exercise requires

2023-11-15 22:56 UTC, dgarijo commented on Assignment4/sofiaferben/task07.py
> +  SELECT DISTINCT ?s ?y
same as above. You are listing the objects and subjects, not the properties

2023-11-15 22:56 UTC, dgarijo commented on Assignment4/sofiaferben/task07.py
> +    print(givenName)
nicely done.

2023-11-27 21:55 UTC, anaigmo commented
Submitted without fixing, no more PRs allowed

2023-11-27 21:55 UTC, merged