Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #216
Opened 2023-10-11 15:34 UTC by juanraromero

2023-11-16 16:37 UTC, anaigmo commented on Assignment4/task07.py
> +  }
missing recursive subclassof relationships

2023-11-16 16:41 UTC, anaigmo commented
The files do not follow the submission instructions, there should be inside a folder with your username and student id. I also left some comments to improve the assignment :)

2023-11-17 17:40 UTC, dgarijo requested changes
Minor changes requested

2023-11-17 17:40 UTC, dgarijo commented on Assignment4/juanraromero-23A248/task07.py
> +for s,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
this does not retireve subclasses of subclasses of living thing. Use a recursive function

2023-11-17 17:40 UTC, dgarijo commented on Assignment4/juanraromero-23A248/task07.py
> +    ?subClass rdfs:subClassOf ns:LivingThing.
same as above. Use `*`

2023-11-17 17:40 UTC, dgarijo commented on Assignment4/juanraromero-23A248/task07.py
> +for s,p,o in g.triples((None, RDFS.subClassOf, ns.Person)):
same as above

2023-11-17 17:40 UTC, dgarijo commented on Assignment4/juanraromero-23A248/task07.py
> +    ?Class rdfs:subClassOf ns:Person.
same as above

2023-11-17 17:40 UTC, dgarijo commented on Assignment4/juanraromero-23A248/task07.py
> +    ?person foaf:knows ns:RockySmith.
the exercise asks for a name, not a URI

2023-11-17 17:40 UTC, dgarijo commented on Assignment4/juanraromero-23A248/task08.py
> +
You are copying the KG in a variable, the operating with that variable. Why not use the KG directly?

2023-11-27 21:46 UTC, anaigmo commented
Submitted and mostly fixed, no more PRs allowed

2023-11-27 21:46 UTC, merged