Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #271
Opened 2023-10-17 11:54 UTC by LauraRamirezM

Please let me know if I'm finally doing the pull request for this assignment correctly.
Thanks in advance.

2023-10-17 12:13 UTC, dgarijo commented
Yes, you are doing the pr correctly

2023-10-31 19:33 UTC, dgarijo requested changes
Nicely done, but some issues to address. Please have a look

2023-10-31 19:33 UTC, dgarijo commented on Assignment4/LauraRamirezM-005955793/task07.py
> +  print(s)
missing all the other subclasses of living thing

2023-10-31 19:33 UTC, dgarijo commented on Assignment4/LauraRamirezM-005955793/task07.py
> +)
missing all the other subclasses of living thing (subclasses of subclasses and so on)

2023-10-31 19:33 UTC, dgarijo commented on Assignment4/LauraRamirezM-005955793/task07.py
> +  print(s2)
This will not print out all the subclasses of subclasses of person. Try doing the function recursively

2023-10-31 19:33 UTC, dgarijo commented on Assignment4/LauraRamirezM-005955793/task07.py
> +  HAVING (COUNT(?entity1) >= 2)
group by and having are not needed here if you have already the filter above.

2023-10-31 19:33 UTC, dgarijo commented on Assignment4/LauraRamirezM-005955793/task08.py
> +
You can load both files in the same graph and do a single query. It's simpler :)

2023-11-27 22:16 UTC, anaigmo commented
Submitted and fixed, no more PRs allowed

2023-11-27 22:16 UTC, merged