Assignment4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #274
Opened 2023-10-17 17:05 UTC by Hugoms-2001

2023-11-16 09:40 UTC, dgarijo requested changes
Changes required. Please have a look

2023-11-16 09:40 UTC, dgarijo commented on Assignment4/Hugoms-2001/task06.py
> +g.add((ns.JaneSmith, VCARD.hasEmail, Literal("jsmith@example.org")))
VCARD does not have this property. Look in the VCARD vocabulary for the right one to use.

2023-11-16 09:40 UTC, dgarijo commented on Assignment4/Hugoms-2001/task07.py
> +    ?SubClass rdfs:subClassOf ns:LivingThing.
this does not address all subclasses of subclasses of living thing. Use `*`

2023-11-16 09:40 UTC, dgarijo commented on Assignment4/Hugoms-2001/task07.py
> +for s, p, o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
same problem as above. Hint: make it recursive

2023-11-16 09:40 UTC, dgarijo commented on Assignment4/Hugoms-2001/task07.py
> +        print (s0)
Same issue as above

2023-11-16 09:40 UTC, dgarijo commented on Assignment4/Hugoms-2001/task07.py
> +    ?Subject foaf:knows ns:RockySmith.
the exercise is asking to return the name of the persons. You are not doing that

2023-11-16 09:40 UTC, dgarijo commented on Assignment4/Hugoms-2001/task07.py
> +
Missing 7.4 and 7.5 in rdflib. Please add them

2023-11-17 11:19 UTC, dgarijo commented
latest commit did not solve issues

2023-11-27 22:19 UTC, anaigmo commented
Submitted and fixed, no more PRs allowed

2023-11-27 22:19 UTC, merged