Assignment 4 aajodar
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #283
Opened 2023-10-18 17:24 UTC by aajodar

2023-11-15 00:14 UTC, dgarijo requested changes
Very small change requests, it's almost perfect. Good job

2023-11-15 00:14 UTC, dgarijo commented on Assignment4/aajodar-22A243/Task07.py
> +    ?s RDFS:subClassOf ns:LivingThing .
what about the subclasses of subclasses of living thing? And so on...

2023-11-15 00:14 UTC, dgarijo commented on Assignment4/aajodar-22A243/Task07.py
> +    print(s)
Nice but make it a recursive function to get all the tree of subclasses

2023-11-15 00:14 UTC, dgarijo commented on Assignment4/aajodar-22A243/Task07.py
> +        print(ind)
This only gets you the subclasses of person, not the subclasses of subclasses like the query below.
The one in sparql is correct, this one is missing small additions

2023-11-15 00:14 UTC, dgarijo commented on Assignment4/aajodar-22A243/Task07.py
> +    ?s RDFS:subClassOf* ns:Person .
the exercise explicitly states that it's not needed to get all the subclass hierarchy...

2023-11-23 21:18 UTC, SerPablo commented
Some minor errors. No more PRs allowed

2023-11-23 21:18 UTC, merged