Reupload of Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #419
Opened 2023-11-17 12:33 UTC by tommasobbb

2023-11-17 16:13 UTC, dgarijo requested changes

2023-11-17 16:13 UTC, dgarijo commented on Assignment4/tommasobbb-CA90299HS/task07.py
> +    ?subclass rdfs:subClassOf ns:LivingThing.
missing all the subclasses of the subclasses of LivingThing. Hint: use `*`

2023-11-17 16:13 UTC, dgarijo commented on Assignment4/tommasobbb-CA90299HS/task07.py
> +  print(s)
same issue as above. Use a recursive function

2023-11-17 16:13 UTC, dgarijo commented on Assignment4/tommasobbb-CA90299HS/task07.py
> +      ?subclass rdfs:subClassOf ns:Person. }
same issue as above

2023-11-17 16:13 UTC, dgarijo commented on Assignment4/tommasobbb-CA90299HS/task07.py
> +  for a, b, c in g.triples((None, RDF.type, s)):
same issue as above

2023-11-17 17:57 UTC, tommasobbb commented
They should be right now

2023-11-17 18:22 UTC, dgarijo requested changes
Closer, but not there yet

2023-11-17 18:22 UTC, dgarijo commented on Assignment4/tommasobbb-CA90299HS/task07.py
> +
missing exercise in rdflib

2023-11-19 23:20 UTC, dgarijo commented on Assignment4/tommasobbb-CA90299HS/task07.py
> +for sub,pred,obj in g.triples((None, RDF.type , Namespace("http://somewhere#").Person)):
Since you have done the previous one ok, I will accept this, even though it's not completely correct

2023-11-19 23:20 UTC, merged