.py corrected
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #421
Opened 2023-11-17 18:36 UTC by LucaBestagno

2023-11-17 18:38 UTC, dgarijo commented
Remove the .DS_store file please!

2023-11-19 23:23 UTC, dgarijo requested changes
Please add remaining exercises

2023-11-19 23:23 UTC, dgarijo commented on Assignment4/luca-bestagno-CA37228OQ/task07.py
> +    ?subclass rdfs:subClassOf ns:LivingThing.
this is not retrieving all subclasses of subclasses of living thing. Use `*`

2023-11-19 23:23 UTC, dgarijo commented on Assignment4/luca-bestagno-CA37228OQ/task07.py
> +    { ?individual rdf:type ?subclass.
same issue as above

2023-11-19 23:23 UTC, dgarijo commented on Assignment4/luca-bestagno-CA37228OQ/task07.py
> +"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""
missing all exercises with rdflib

2023-11-23 17:57 UTC, SerPablo commented
Delivered with some error, no more PRs allowed. Rdflib and small errors.

2023-11-23 17:57 UTC, merged