Reupload Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #422
Opened 2023-11-17 18:40 UTC by AlexRouge

Unfortunately, speaking with some of my colleagues, I only realized today that my previous pull request dated October 9th was not only empty but closed by itself even though I was sure I had done things correctly. I understand very well if assignment 4 is not accepted now but I assure you that I've done everything before the deadline. I hope you can understand, have a good evening

2023-11-17 18:47 UTC, dgarijo commented
No worries. However you are uploading notebooks, which does not follow the
instructions shown in class. Please upload the correct files ( see the
slides)

El vie., 17 nov. 2023 7:40 p. m., AlexRouge ***@***.***>
escribió:

> Unfortunately, speaking with some of my colleagues, I only realized today
> that my previous pull request dated October 9th was not only empty but
> closed by itself even though I was sure I had done things correctly. I
> understand very well if assignment 4 is not accepted now but I assure you
> that I've done everything before the deadline. I hope you can understand,
> have a good evening
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422
> Commit Summary
>
>    - 22f9672
>    <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422/commits/22f9672e02dad8abb539a0ecadf053145b4332f1>
>    Reupload Assignment 4
>
> File Changes
>
> (5 files
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422/files>
> )
>
>    - *M* Assignment4/.DS_Store
>    <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422/files#diff-f0fa516e8cbe8fe4015044d0a1c2b60a0e8500151a54fb258bd07767f1f66bbc>
>    (0)
>    - *A* Assignment4/AlexRouge - CA43899MT/Task06.ipynb
>    <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422/files#diff-c111186ddf9da0e04b1dc61b98b9e168e7743b5a9ffe520579a7ac21b05817b8>
>    (229)
>    - *A* Assignment4/AlexRouge - CA43899MT/Task07.ipynb
>    <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422/files#diff-5cf0c7aeae89817567a53706bb256dfd23c9959ca9f1d7449994f63d0e825450>
>    (215)
>    - *A* Assignment4/AlexRouge - CA43899MT/Task08.ipynb
>    <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422/files#diff-416ba954a83b9bf6b0315ce86b927c93962ad54e5ea3bb26f4530ee1aec70759>
>    (104)
>    - *A* Assignment4/AlexRouge - CA43899MT/Task09.ipynb
>    <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422/files#diff-d00e6122a821dc0c0f9c9189ef30317e06f57389c37446d31491232c3ae86caa>
>    (118)
>
> Patch Links:
>
>    -
>    https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422.patch
>    -
>    https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/422>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALTIGUUVS3TC3AEQJSMX33YE6VQ7AVCNFSM6AAAAAA7QGMPHWVHI2DSMVQWIX3LMV43ASLTON2WKOZRHE4TSNZRGQ2DGOA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***
> com>
>

2023-11-17 19:15 UTC, AlexRouge commented
Now they should have been uploaded in the correct format; thank you again for your comprehension

2023-11-20 11:34 UTC, dgarijo requested changes
Please address remaining issues and remove the ds store file

2023-11-20 11:34 UTC, dgarijo commented on Assignment4/.DS_Store
Remove this file

2023-11-20 11:34 UTC, dgarijo commented on Assignment4/AlexRouge - CA43899MT/task07.py
> +for s, p, o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
This does not provide the same results as the previous sparql function. Use a recursive function

2023-11-20 11:34 UTC, dgarijo commented on Assignment4/AlexRouge - CA43899MT/task07.py
> +for s, p, o in g.triples((None, RDF.type, ns.Person)):
Same problem as above

2023-11-20 11:34 UTC, dgarijo commented on Assignment4/AlexRouge - CA43899MT/task07.py
> +  print(row)
Missing 7.4 and 7.5 in rdflib

2023-11-21 22:45 UTC, dgarijo approved these changes

2023-11-21 22:45 UTC, merged