Assignment4 - Álvaro Alonso Lancho
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #425
Opened 2023-11-17 19:08 UTC by b190057

2023-11-19 23:28 UTC, dgarijo requested changes
There are errors and missing exercises

2023-11-19 23:28 UTC, dgarijo commented on Assignment4/b190057-b190057/task07.py
> +
Missing all exercises in rdflib

2023-11-19 23:28 UTC, dgarijo commented on Assignment4/b190057-b190057/task07.py
> +        ?subclass rdfs:subClassOf ns:LivingThing
You should print also the subclasses of subclasses of LivingThing

2023-11-19 23:28 UTC, dgarijo commented on Assignment4/b190057-b190057/task07.py
> +    HAVING (COUNT(?p1) > 1)""", initNs={"foaf":FOAF}
Did you try this query? `?2` does not look correct, as it's not a correct variable name. Also, the group, having and count are not needed here

2023-11-23 18:15 UTC, SerPablo commented
Delivered, no more PRs allowed

2023-11-23 18:15 UTC, merged