Assignment 4 - b19M057
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #430
Opened 2023-11-19 16:44 UTC by pmad19

2023-11-19 16:50 UTC, pmad19 commented
@dgarijo This is the new pull request for Assignment 4. I have separated the two commits in two pull request as you commented me in https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/204. I have also close the old pull request https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/204 and https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/285

2023-11-20 12:04 UTC, dgarijo requested changes
Task 7 is incomplete

2023-11-20 12:04 UTC, dgarijo commented on Assignment4/pmad19-b19M057/task07.py
> +    ?Subject rdfs:subClassOf ns:LivingThing
this does not retrieve all subclasses of subclasses of LivingThing

2023-11-20 12:04 UTC, dgarijo commented on Assignment4/pmad19-b19M057/task07.py
> +    individuals.append(individual)
same as above

2023-11-20 12:04 UTC, dgarijo commented on Assignment4/pmad19-b19M057/task07.py
> +"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**
You are not doing the right exercises. This is taken from last year.

2023-11-20 12:04 UTC, dgarijo commented on Assignment4/pmad19-b19M057/task07.py
> +"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**
7.3, 7.4 and 7.5 missing.
Also, exercises are missing in rdflib

2023-11-23 21:23 UTC, SerPablo commented
Errors not solved. Pull request closed. No more PR are allowed

2023-11-23 21:23 UTC, closed without merging