Assignment4
FacultadInformatica-LinkedData/Curso2023-2024-ODKG pull request #94
Opened 2023-10-03 10:58 UTC by enrimmartel

2023-11-17 11:57 UTC, dgarijo requested changes
Please address pending changes

2023-11-18 16:37 UTC, enrimmartel commented on Assignment4/enrimmartel-23A254/task06.py
> +g.add((ns.JohnSmith, vcard.WorkFor, ns.UPM))
I have looked for a new property. In this case it is hasPost.

2023-11-18 17:43 UTC, enrimmartel commented on Assignment4/enrimmartel-23A254/task07.py
> +    print(s)
Updated

2023-11-18 17:43 UTC, enrimmartel commented on Assignment4/enrimmartel-23A254/task07.py
> +        ?subClass rdfs:subClassOf ns:LivingThing .
Updated

2023-11-18 17:43 UTC, enrimmartel commented on Assignment4/enrimmartel-23A254/task07.py
> +)
Updated

2023-11-18 17:43 UTC, enrimmartel commented on Assignment4/enrimmartel-23A254/task07.py
> +          ?i rdf:type ?subClass.
Updated

2023-11-18 17:43 UTC, enrimmartel commented on Assignment4/enrimmartel-23A254/task07.py
> +  print(s)
Updated

2023-11-18 17:44 UTC, enrimmartel commented
Updated

2023-11-18 17:52 UTC, enrimmartel commented
Comments processed :)


---
Enrique

El 2023-11-17 12:57, Daniel Garijo escribió:
> @dgarijo requested changes on this pull request.
> 
> Please address pending changes
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task06.py [1]:
> 
>> +
> +g.add((ns.JaneSmith, vcard.Email, ***@***.***")))
> +g.add((ns.JaneSmith, vcard.FN, Literal("Jane Smith")))
> +g.add((ns.JaneSmith, vcard.Given, Literal("Jane")))
> +g.add((ns.JaneSmith, vcard.Family, Literal("Smith")))
> +
> +# Visualize the results
> +for s, p, o in g:
> +  print(s,p,o)
> +
> +"""**TASK 6.5: Add UPM as the university where John Smith works**"""
> +
> +# TO DO
> +
> +g.add((ns.UPM, RDF.type, ns.University))
> +g.add((ns.JohnSmith, vcard.WorkFor, ns.UPM))
> 
> vcard does not define WorkFor. Either look for another property that
> is suitable, or create your own
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [2]:
> 
>> +from rdflib.namespace import RDF, RDFS
> +g = Graph()
> +g.namespace_manager.bind('ns', Namespace("http://somewhere#"),
> override=False)
> +g.namespace_manager.bind('vcard',
> Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
> +g.parse(github_storage+"/rdf/example6.rdf", format="xml")
> +
> +"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and
> SPARQL**"""
> +
> +# TO DO
> +from rdflib.plugins.sparql import prepareQuery
> +
> +# 1) RDFLib
> +print("---RDFLib---")
> +ns = Namespace("http://somewhere#")
> +for s, p, o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
> +    print(s)
> 
> missing the subclasses of subclasses of LivingThing. Hint: create a
> recursive function
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [3]:
> 
>> +from rdflib.plugins.sparql import prepareQuery
> +
> +# 1) RDFLib
> +print("---RDFLib---")
> +ns = Namespace("http://somewhere#")
> +for s, p, o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
> +    print(s)
> +
> +
> +# 2) SPARQL
> +print("---SPARQL---")
> +
> +q1 = prepareQuery('''
> +    SELECT ?subClass
> +    WHERE {
> +        ?subClass rdfs:subClassOf ns:LivingThing .
> 
> same issue as above. Use *
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [4]:
> 
>> +        print(s)
> +
> +
> +# 2) SPARQL
> +print("---SPARQL---")
> +#Individuals of Person
> +q2a = prepareQuery('''
> +    SELECT ?i
> +    WHERE {
> +        {
> +          ?i rdf:type ns:Person.
> +        }
> +    }
> +    ''',
> +    initNs={"rdf": RDF, "rdfs": RDFS, "ns": ns}
> +)
> 
> Same issue as above for both exercises. What about the subclasses?
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [5]:
> 
>> +)
> +for r in g.query(q2a):
> +  print(r.i)
> +
> +print("-------")
> +
> +#Individuals of Person + individuals of subclassesof Person
> +q2b = prepareQuery('''
> +    SELECT ?i
> +    WHERE {
> +        {
> +          ?i rdf:type ns:Person.
> +        }
> +        UNION
> +        {
> +          ?i rdf:type ?subClass.
> 
> use * to get all subclasses
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [6]:
> 
>> +  print(r.i)
> +
> +"""**TASK 7.3: List all individuals of "Person" or "Animal" and all
> their properties including their class with RDFLib and SPARQL. You do
> not need to list the individuals of the subclasses of person**
> +
> +"""
> +
> +# TO DO
> +# Visualize the results
> +
> +# 1) RDFLib
> +print("---RDFLib---")
> +ns = Namespace("http://somewhere#")
> +
> +#Individuals of Person
> +for s,p,o in g.triples((None,RDF.type,ns.Person)):
> +  print(s)
> 
> where is the listing of their properties?
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [7]:
> 
>> +q3 = prepareQuery('''
> +    SELECT ?x
> +    WHERE {
> +        {
> +          ?x rdf:type ns:Person .
> +        }
> +        UNION
> +        {
> +          ?x rdf:type ns:Animal .
> +        }
> +    }
> +    ''',
> +    initNs={"rdf": RDF, "rdfs": RDFS, "ns": ns}
> +)
> +for r in g.query(q3):
> +  print(r.x)
> 
> you are only listing subjects. Follow the exercise, please
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [8]:
> 
>> +# 1) RDFLib
> +ns = Namespace("http://somewhere#")
> +
> +
> +print("---RDFLib---")
> +for s, p, o in g.triples((None, FOAF.knows, ns.RockySmith)):
> +        print(s)
> +
> +print("---SPARQL---")
> +
> +# 2) SPARQL
> +q4 = prepareQuery('''
> +    SELECT DISTINCT ?x
> +    WHERE {
> +        {
> +          ?x foaf:knows ns:RockySmith .
> 
> exercise is asking for the name of the person(s) who knows Rocky.
> Other animals may know Rocky
> -------------------------
> 
> In Assignment4/enrimmartel-23A254/task07.py [9]:
> 
>> +"""**Task 7.5: List the entities who know at least two other
> entities in the graph**"""
> +
> +# TO DO
> +# Visualize the results
> +
> +# 2) SPARQL
> +print("---SPARQL---")
> +q5 = prepareQuery('''
> +    SELECT ?entity
> +    WHERE {
> +      ?entity foaf:knows ?person1 .
> +      ?entity foaf:knows ?person2 .
> +      FILTER (?person1 != ?person2)
> +    }
> +    GROUP BY ?entity
> +    HAVING (COUNT(?person1) >= 2)
> 
> The whole GROUP BY, HAVING, etc is not needed here.
> Also, missing in rdflib
> 
> --
> Reply to this email directly, view it on GitHub [10], or unsubscribe
> [11].
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
> 
> 
> Links:
> ------
> [1] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394997557
> [2] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394997767
> [3] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394997849
> [4] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394998092
> [5] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394998456
> [6] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394998706
> [7] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394998948
> [8] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394999199
> [9] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#discussion_r1394999754
> [10] 
> https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-ODKG/pull/94#pullrequestreview-1733247421
> [11] 
> https://github.com/notifications/unsubscribe-auth/BCSKLSN5YLGBBGJFKIFDTWLYE5GKPAVCNFSM6AAAAAA5QZLYCCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZTGI2DONBSGE

2023-11-20 11:43 UTC, dgarijo approved these changes

2023-11-20 11:43 UTC, merged